In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("Amazon Books Data.csv")
df.head()

,title,description,author,isbn10,isbn13,publish_date,edition,best_seller,top_rated,rating,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,The Staff Engineer's Path,A Guide for Individual Contributors Navigating...,Tanya Reilly,1098118731,978-1098118730,2022-10-25,1,Yes,No,4.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Cracking the Coding Interview,189 Programming Questions and Solutions,Gayle Laakmann McDowell,984782869,978-0984782857,2015-07-01,6,Yes,No,4.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Python Crash Course, 3rd Edition","A Hands-On, Project-Based Introduction to Prog...",Eric Matthes,1718502702,978-1718502703,2023-01-10,3,Yes,No,4.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,The Pragmatic Programmer,"20th Anniversary Edition, 2nd Edition: Your Jo...",David Thomas,NaN,978-0135957059,2019-09-13,2,Yes,No,4.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Clean Code,A Handbook of Agile Software Craftsmanship,Robert C. Martin,NaN,978-0132350884,2008-08-01,1,Yes,No,4.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df = df.loc[:, df.columns[~df.columns.str.contains('^Unnamed')]]
print("Columns after removal of unnecessary ones:")
print(df.columns)
df.head()

Columns after removal of unnecessary ones:
Index(['title', 'description', 'author', 'isbn10', 'isbn13', 'publish_date',
       'edition', 'best_seller', 'top_rated ', 'rating', 'review_count',
       'price'],
      dtype='object')

,title,description,author,isbn10,isbn13,publish_date,edition,best_seller,top_rated,rating,review_count,price
0,The Staff Engineer's Path,A Guide for Individual Contributors Navigating...,Tanya Reilly,1098118731,978-1098118730,2022-10-25,1,Yes,No,4.7,189,$31.99
1,Cracking the Coding Interview,189 Programming Questions and Solutions,Gayle Laakmann McDowell,984782869,978-0984782857,2015-07-01,6,Yes,No,4.7,8334,$33.21
2,"Python Crash Course, 3rd Edition","A Hands-On, Project-Based Introduction to Prog...",Eric Matthes,1718502702,978-1718502703,2023-01-10,3,Yes,No,4.8,165,$30.61
3,The Pragmatic Programmer,"20th Anniversary Edition, 2nd Edition: Your Jo...",David Thomas,NaN,978-0135957059,2019-09-13,2,Yes,No,4.8,2521,$38.00
4,Clean Code,A Handbook of Agile Software Craftsmanship,Robert C. Martin,NaN,978-0132350884,2008-08-01,1,Yes,No,4.7,5639,$40.00

In [5]:
df_cleaned = df.dropna(how='all')
print(df_cleaned)

                                title  \
0           The Staff Engineer's Path
1       Cracking the Coding Interview
2    Python Crash Course, 3rd Edition
3            The Pragmatic Programmer
4                          Clean Code
..                                ...
462                       Programming
463             Transitioning to Java
464                              Java
465         Learn Java 17 Programming
466          Learning Spring Boot 3.0

                                           description  \
0    A Guide for Individual Contributors Navigating...
1              189 Programming Questions and Solutions
2    A Hands-On, Project-Based Introduction to Prog...
3    20th Anniversary Edition, 2nd Edition: Your Jo...
4           A Handbook of Agile Software Craftsmanship
..                                                 ...
462  4 Manuscripts in 1 book: Python For Beginners,...
463  Kickstart your polyglot programming journey by...
464  The Ultimate Beginner's Guide to Learn Java Qu...
465  Learn the fundamentals of Java Programming wit...
466  Simplify the development of production-grade a...

                      author      isbn10          isbn13 publish_date edition  \
0               Tanya Reilly  1098118731  978-1098118730   2022-10-25       1
1    Gayle Laakmann McDowell   984782869  978-0984782857   2015-07-01       6
2               Eric Matthes  1718502702  978-1718502703   2023-01-10       3
3               David Thomas         NaN  978-0135957059   2019-09-13       2
4           Robert C. Martin         NaN  978-0132350884   2008-08-01       1
..                       ...         ...             ...          ...     ...
462       Timothy C. Needham  1728914671  978-1728914671    17-Oct-18       1
463                Ken Fogel  1804614017  978-1804614013    28-Apr-23       1
464                Mark Reed         NaN  979-8387893131    21-Mar-23       1
465            Nick Samoylov  1803241438  978-1803241432    29-Jul-22       2
466        Greg L. Turnquist  1803233303  978-1803233307    30-Dec-22       3

    best_seller top_rated  rating review_count    price
0           Yes         No    4.7          189   $31.99
1           Yes         No    4.7         8334   $33.21
2           Yes         No    4.8          165   $30.61
3           Yes         No    4.8         2521   $38.00
4           Yes         No    4.7         5639   $40.00
..          ...        ...    ...          ...      ...
462          No         No    4.4         2167  $27.97
463          No         No    4.5            2  $44.99
464          No         No      5          162  $24.99
465          No         No    4.3           17  $39.99
466          No         No    4.4           18  $37.49

[467 rows x 12 columns]

In [6]:
df.shape

(541, 12)

In [8]:
# Check for missing values
missing_values = df.isnull().sum()
print("\nMissing Values:\n", missing_values)

Missing Values:
 title            75
description     154
author           76
isbn10          175
isbn13           76
publish_date     78
edition          77
best_seller      74
top_rated        74
rating           78
review_count     78
price            77
dtype: int64

In [9]:
# Get descriptive statistics for numerical columns
statistics = df.describe()
print("Initial Statistics:\n", statistics)

Initial Statistics:
                              title  \
count                          466
unique                         418
top     Python Programming and SQL
freq                             4

                                          description     author      isbn10  \
count                                             387        465         366
unique                                            355        410         338
top     Elements of Reusable Object-Oriented Software  Mark Reed  1803237066
freq                                                3          5           3

                isbn13 publish_date edition best_seller top_rated  rating  \
count              465          463     464         467        467    463
unique             429          360      12           7          3     22
top     979-8373278850   2023-01-10       1          No         No    4.7
freq                 3            6     351         323        442     98

       review_count   price
count           463     464
unique          300     281
top               5  $44.99
freq              8      16

In [10]:
# Check data types and dimensions of the dataset
print("\nData Types:\n", df.dtypes)
print("\nData Dimensions:", df.shape)

Data Types:
 title           object
description     object
author          object
isbn10          object
isbn13          object
publish_date    object
edition         object
best_seller     object
top_rated       object
rating          object
review_count    object
price           object
dtype: object

Data Dimensions: (541, 12)

In [11]:
# Summarize the types of variables
print("\nVariable Data Types:\n", df.dtypes)

Variable Data Types:
 title           object
description     object
author          object
isbn10          object
isbn13          object
publish_date    object
edition         object
best_seller     object
top_rated       object
rating          object
review_count    object
price           object
dtype: object

In [39]:
# Convert rating and review_count to numeric ,'edition'
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')  # Converts to float
df['review_count'] = pd.to_numeric(df['review_count'], errors='coerce')  # Converts to float
df['review_count'] = df['review_count'].fillna(0).astype('int64')  # Fill NaN with 0 and convert to int64
df['edition'] = pd.to_numeric(df['review_count'], errors='coerce')  # Converts to float
df['edition'] = df['review_count'].fillna(0).astype('int64')  # Fill NaN with 0 and convert to int64

print(df.dtypes)

title                              object
description                        object
author                             object
isbn10                             object
isbn13                             object
publish_date               datetime64[ns]
edition                             int64
best_seller                         int64
top_rated                          object
rating                            float64
review_count                        int64
price                             float64
(review_count, edition)             int64
dtype: object

In [40]:
# Convert price to numeric by removing currency symbols
df['price'] = df['price'].replace({'\$': '', ',': ''}, regex=True)
df['price'] = pd.to_numeric(df['price'], errors='coerce')  # Converts to float
print(df.dtypes)

title                              object
description                        object
author                             object
isbn10                             object
isbn13                             object
publish_date               datetime64[ns]
edition                             int64
best_seller                         int64
top_rated                          object
rating                            float64
review_count                        int64
price                             float64
(review_count, edition)             int64
dtype: object

In [41]:
# Convert publish_dat to datetime
df['publish_date'] = pd.to_datetime(df['publish_date'], errors='coerce')
print(df.dtypes)

title                              object
description                        object
author                             object
isbn10                             object
isbn13                             object
publish_date               datetime64[ns]
edition                             int64
best_seller                         int64
top_rated                          object
rating                            float64
review_count                        int64
price                             float64
(review_count, edition)             int64
dtype: object

In [23]:
# Importing SimpleImputer from sklearn for handling missing values
from sklearn.impute import SimpleImputer

# Handle missing values in numerical columns using the median
numerical_columns = ['rating', 'review_count', 'price','edition']
imputer_numerical = SimpleImputer(strategy='median')
df[numerical_columns] = imputer_numerical.fit_transform(df[numerical_columns])

# Handle missing values in categorical columns using the mode (most frequent value)
categorical_columns = ['title', 'description', 'author', 'isbn10','isbn13','best_seller']
imputer_categorical = SimpleImputer(strategy='most_frequent')
df[categorical_columns] = imputer_categorical.fit_transform(df[categorical_columns])

# Check if there are any remaining missing values
missing_values_after_imputation = df.isnull().sum()
print("Missing Values After Imputation:\n", missing_values_after_imputation)

# Display the updated dataset
df.head()

Missing Values After Imputation:
 title            0
description      0
author           0
isbn10           0
isbn13           0
publish_date    82
edition          0
best_seller      0
top_rated       74
rating           0
review_count     0
price            0
dtype: int64

,title,description,author,isbn10,isbn13,publish_date,edition,best_seller,top_rated,rating,review_count,price
0,The Staff Engineer's Path,A Guide for Individual Contributors Navigating...,Tanya Reilly,1098118731,978-1098118730,2022-10-25,1,Yes,No,4.7,189.0,31.99
1,Cracking the Coding Interview,189 Programming Questions and Solutions,Gayle Laakmann McDowell,984782869,978-0984782857,2015-07-01,6,Yes,No,4.7,8334.0,33.21
2,"Python Crash Course, 3rd Edition","A Hands-On, Project-Based Introduction to Prog...",Eric Matthes,1718502702,978-1718502703,2023-01-10,3,Yes,No,4.8,165.0,30.61
3,The Pragmatic Programmer,"20th Anniversary Edition, 2nd Edition: Your Jo...",David Thomas,1617296864,978-0135957059,2019-09-13,2,Yes,No,4.8,2521.0,38.00
4,Clean Code,A Handbook of Agile Software Craftsmanship,Robert C. Martin,1617296864,978-0132350884,2008-08-01,1,Yes,No,4.7,5639.0,40.00

In [42]:
if 'top_rated' in df.columns:
    df['top_rated'] = df['top_rated'].fillna(df['top_rated'].mode()[0])
else:
    print("'top_rated' column not found.")

'top_rated' column not found.

In [31]:
# Impute publish_date by converting it to datetime and use a mode imputation
df['publish_date'] = pd.to_datetime(df['publish_date'], errors='coerce')
df['publish_date'] = df['publish_date'].fillna(df['publish_date'].mode()[0])

# Impute 'top_rated' with the mode (most frequent value)
#df['top_rated'] = df['top_rated'].fillna('No')

# Check if there are any remaining missing values
missing_values_after_imputation = df.isnull().sum()
print("Missing Values After Imputation:\n", missing_values_after_imputation)

# Display the updated dataset
df.head()

Missing Values After Imputation:
 title            0
description      0
author           0
isbn10           0
isbn13           0
publish_date     0
edition          0
best_seller      0
top_rated       74
rating           0
review_count     0
price            0
dtype: int64

,title,description,author,isbn10,isbn13,publish_date,edition,best_seller,top_rated,rating,review_count,price
0,The Staff Engineer's Path,A Guide for Individual Contributors Navigating...,Tanya Reilly,1098118731,978-1098118730,2022-10-25,1,Yes,No,4.7,189.0,31.99
1,Cracking the Coding Interview,189 Programming Questions and Solutions,Gayle Laakmann McDowell,984782869,978-0984782857,2015-07-01,6,Yes,No,4.7,8334.0,33.21
2,"Python Crash Course, 3rd Edition","A Hands-On, Project-Based Introduction to Prog...",Eric Matthes,1718502702,978-1718502703,2023-01-10,3,Yes,No,4.8,165.0,30.61
3,The Pragmatic Programmer,"20th Anniversary Edition, 2nd Edition: Your Jo...",David Thomas,1617296864,978-0135957059,2019-09-13,2,Yes,No,4.8,2521.0,38.00
4,Clean Code,A Handbook of Agile Software Craftsmanship,Robert C. Martin,1617296864,978-0132350884,2008-08-01,1,Yes,No,4.7,5639.0,40.00

In [43]:
from sklearn.preprocessing import StandardScaler

# Normalize numerical columns
scaler = StandardScaler()
df[['rating', 'review_count', 'price','edition']] = scaler.fit_transform(df[['rating', 'review_count', 'price','edition']])

# Display the normalized data
print("\nNormalized Numerical Columns:\n", df[['rating', 'review_count', 'price','edition']].head())

Normalized Numerical Columns:
      rating  review_count     price   edition
0  0.324069     -0.072039 -0.000896 -0.072039
1  0.324069      2.093139  0.084693  2.093139
2  0.497654     -0.072039 -0.097710 -0.072039
3  0.497654     -0.072039  0.420735 -0.072039
4  0.324069      1.010550  0.561045  1.010550

In [45]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Encode categorical columns with LabelEncoder (or OneHotEncoder)
label_encoder = LabelEncoder()
df['best_seller'] = label_encoder.fit_transform(df['best_seller'])

# For the remaining categorical columns, apply one-hot encoding
df_encoded = pd.get_dummies(df, columns=['title', 'description', 'author', 'isbn10', 'isbn13', 'publish_date'])

# Display the transformed DataFrame
print("\nTransformed DataFrame:\n", df_encoded)

Transformed DataFrame:
       edition  best_seller top_rated     rating  review_count     price  \
0   -0.072039            3         No  0.324069     -0.072039 -0.000896
1    2.093139            3         No  0.324069      2.093139  0.084693
2   -0.072039            3         No  0.497654     -0.072039 -0.097710
3   -0.072039            3         No  0.497654     -0.072039  0.420735
4    1.010550            3         No  0.324069      1.010550  0.561045
..        ...          ...        ...       ...           ...       ...
536 -0.072039            1        NaN  0.150483     -0.072039 -0.109636
537 -0.072039            1        NaN  0.150483     -0.072039 -0.109636
538 -0.072039            1        NaN  0.150483     -0.072039 -0.109636
539 -0.072039            1        NaN  0.150483     -0.072039 -0.109636
540 -0.072039            1        NaN  0.150483     -0.072039 -0.109636

     (review_count, edition)  \
0                          0
1                          2
2                          0
3                          0
4                          1
..                       ...
536                        0
537                        0
538                        0
539                        0
540                        0

     title_(ISC)2 CISSP Certified Information Systems Security Professional Official Study Guide & Practice Tests Bundle  \
0                                                    0
1                                                    0
2                                                    0
3                                                    0
4                                                    0
..                                                 ...
536                                                  0
537                                                  0
538                                                  0
539                                                  0
540                                                  0

     title_.NET MAUI Cross-Platform Application Development  \
0                                                    0
1                                                    0
2                                                    0
3                                                    0
4                                                    0
..                                                 ...
536                                                  0
537                                                  0
538                                                  0
539                                                  0
540                                                  0

     title_100 Go Mistakes and How to Avoid Them  ...  \
0                                              0  ...
1                                              0  ...
2                                              0  ...
3                                              0  ...
4                                              0  ...
..                                           ...  ...
536                                            0  ...
537                                            0  ...
538                                            0  ...
539                                            0  ...
540                                            0  ...

     publish_date_2023-05-06 00:00:00  publish_date_2023-05-07 00:00:00  \
0                                   0                                 0
1                                   0                                 0
2                                   0                                 0
3                                   0                                 0
4                                   0                                 0
..                                ...                               ...
536                                 0                                 0
537                                 0                                 0
538                                 0                                 0
539                                 0                                 0
540                                 0                                 0

     publish_date_2023-05-08 00:00:00  publish_date_2023-05-09 00:00:00  \
0                                   0                                 0
1                                   0                                 0
2                                   0                                 0
3                                   0                                 0
4                                   0                                 0
..                                ...                               ...
536                                 0                                 0
537                                 0                                 0
538                                 0                                 0
539                                 0                                 0
540                                 0                                 0

     publish_date_2023-05-10 00:00:00  publish_date_2023-05-11 00:00:00  \
0                                   0                                 0
1                                   0                                 0
2                                   0                                 0
3                                   0                                 0
4                                   0                                 0
..                                ...                               ...
536                                 0                                 0
537                                 0                                 0
538                                 0                                 0
539                                 0                                 0
540                                 0                                 0

     publish_date_2023-05-16 00:00:00  publish_date_2023-05-17 00:00:00  \
0                                   0                                 0
1                                   0                                 0
2                                   0                                 0
3                                   0                                 0
4                                   0                                 0
..                                ...                               ...
536                                 0                                 0
537                                 0                                 0
538                                 0                                 0
539                                 0                                 0
540                                 0                                 0

     publish_date_2023-05-23 00:00:00  publish_date_2023-06-06 00:00:00
0                                   0                                 0
1                                   0                                 0
2                                   0                                 0
3                                   0                                 0
4                                   0                                 0
..                                ...                               ...
536                                 0                                 0
537                                 0                                 0
538                                 0                                 0
539                                 0                                 0
540                                 0                                 0

[541 rows x 2307 columns]